calibration:
  bayesian:
    n_samples: 1000
    noise_scale: 1.0
    proposal_scale: 0.1
  optimization:
    max_iterations: 100
    method: differential_evolution
    mutation_rate: 0.5
    population_size: 20
    recombination_rate: 0.7
  parameters:
    bond_strength:
      bounds:
      - 5e5
      - 2e6
      distribution: normal
      initial_value: 1e6
      scale: 2e5
    fluid_density:
      bounds:
      - 900.0
      - 1100.0
      distribution: normal
      initial_value: 1000.0
      scale: 50.0
    fluid_viscosity:
      bounds:
      - 0.0005
      - 0.002
      distribution: normal
      initial_value: 0.001
      scale: 0.0002
    particle_radius:
      bounds:
      - 0.005
      - 0.02
      distribution: uniform
      initial_value: 0.01
case_study:
  mud_concentration: 0.1
  tunnel:
    center:
    - 50.0
    - 25.0
    - 25.0
    diameter: 5.0
    length: 50.0
  water_pressure:
    inlet: 1.0e6
    outlet: 1.0e5
cfd:
  boundary_conditions:
    type: no-slip
    velocity:
    - 0.0
    - 0.0
    - 0.0
  fluid_density: 1100.0
  fluid_viscosity: 0.002
  pressure_gradient:
  - 1.0
  - 0.0
  - 0.0
  pressure_solver:
    max_iterations: 1000
    tolerance: 1e-6
  turbulence_model: k-epsilon
  velocity_solver:
    max_iterations: 1000
    tolerance: 1e-6
  wall_roughness: 0.001
coarse_grained:
  calibration_file: data/calibrated_params.json
  clustering:
    distance_threshold: 0.1
    method: hierarchical
  force_scale: 8.0
  length_scale: 10.0
  mapping:
    interpolation_order: 1
    smoothing: true
  time_scale: 5.0
coupling:
  critical_force: 1.0
  drag_model: schiller_naumann
  force_coupling: true
  heat_coupling: false
  interpolation_order: 1
  interval: 1
  lift_model: saffman
  mass_coupling: false
  virtual_mass: true
dem:
  bond_radius: 0.015
  bond_strength: 2000000.0
  damping_coefficient: 0.1
  friction_coefficient: 0.5
  particle_density: 2650.0
  particle_radius: 0.009
  poisson_ratio: 0.3
  restitution_coefficient: 0.7
  youngs_modulus: 1e9
erosion:
  bond_degradation_rate: 0.1
  critical_shear_stress: 1.0
  deposition_rate: 0.1
  erosion_rate_coefficient: 1.0e-06
  particle_detachment_threshold: 0.1
  particle_removal_threshold: 0.1
  transport_capacity: 1.0
experimental:
  data_processing:
    cutoff_frequency: 10.0
    filter_order: 4
    filter_type: butterworth
  erosion_points: 4
  measurement_duration: 10.0
  output:
    data_format: numpy
    directory: results/experimental
    plot_format: png
    save_plots: true
    save_processed_data: true
    save_raw_data: true
  pressure_points: 5
  sampling_rate: 100
  sensor_noise:
    erosion: 0.1
    pressure: 0.01
    velocity: 0.05
  velocity_points: 3
geotechnical:
  Cc: 15.0
  Cu: 9.840000000000003
  clay_content: 14.910000000000002
  cohesion: 25.56
  density: 0.8099999999999999
  friction_angle: 23.95
  grain_sizes:
  - 10.0
  - 5.0
  - 2.0
  - 1.0
  - 0.5
  - 0.1
  passing_percentages:
  - 100.0
  - 90.0
  - 60.0
  - 40.0
  - 20.0
  - 5.0
  permeability: -0.039998900000000004
  specific_gravity: 3.22
  water_content: 7.8700000000000045
mitigation:
  optimization:
    constraints:
      max_cost: 1000000
      max_time: 14
      min_effectiveness: 0.7
    weights:
      cost_weight: 0.4
      effectiveness_weight: 0.4
      time_weight: 0.2
  output:
    data_format: json
    directory: results/mitigation
    plot_format: png
    save_optimization_results: true
    save_plots: true
    save_strategy_results: true
  strategies:
  - cost_model:
      equipment_cost: 50000
      labor_cost: 500
      maintenance_cost: 1000
      material_cost: 1000
    effectiveness_model:
      base_flow: 1.0
      base_pressure: 1e6
      flow_weight: 0.3
      pressure_weight: 0.4
      stability_weight: 0.3
      target_stability: 1.5
    name: grouting
    parameters:
      implementation_time: 7
      permeability_reduction: 0.1
      porosity_reduction: 0.3
      strength_increase: 2e6
    type: grouting
  - cost_model:
      equipment_cost: 30000
      labor_cost: 300
      maintenance_cost: 500
      material_cost: 500
    effectiveness_model:
      base_flow: 1.0
      base_pressure: 1e6
      flow_weight: 0.4
      pressure_weight: 0.5
      stability_weight: 0.1
      target_stability: 1.2
    name: drainage
    parameters:
      channel_positions:
      - - 0
        - 0
        - 0
      - - 20
        - 0
        - 0
      - - 40
        - 0
        - 0
      - - 60
        - 0
        - 0
      flow_reduction: 0.6
      implementation_time: 5
      pressure_reduction: 0.5
    type: drainage
  - cost_model:
      equipment_cost: 40000
      labor_cost: 400
      maintenance_cost: 2000
      material_cost: 2000
    effectiveness_model:
      base_flow: 1.0
      base_pressure: 1e6
      flow_weight: 0.2
      pressure_weight: 0.2
      stability_weight: 0.6
      target_stability: 1.8
    name: support
    parameters:
      deformation_reduction: 0.8
      element_positions:
      - - 0
        - 0
        - 0
      - - 10
        - 0
        - 0
      - - 20
        - 0
        - 0
      - - 30
        - 0
        - 0
      - - 40
        - 0
        - 0
      - - 50
        - 0
        - 0
      - - 60
        - 0
        - 0
      - - 70
        - 0
        - 0
      implementation_time: 10
      stress_reduction: 0.7
    type: support
output:
  directory: results
  format: numpy
  save_fluid: true
  save_interval: 0.1
  save_particles: true
  visualization:
    enabled: true
    format: png
    interval: 0.5
    variables:
    - velocity
    - pressure
    - erosion_rate
  visualization_interval: 10
parallel:
  amr_buffer_cells: 2
  coarsening_threshold: 0.01
  communication:
    async_communication: true
    buffer_size: 1024
  load_balancing:
    interval: 100
    method: dynamic
    threshold: 0.1
  max_amr_level: 3
  num_ranks: 8
  output:
    directory: results/parallel
    performance_metrics:
    - wall_time
    - cpu_time
    - memory_usage
    - communication_time
    - load_balance
    save_amr_grid: true
    save_decomposition: true
    save_metrics: true
    save_performance: true
  refinement_threshold: 0.1
simulation:
  domain_size:
  - 100.0
  - 50.0
  - 50.0
  gravity:
  - 0.0
  - -9.81
  - 0.0
  grid_resolution:
  - 101
  - 51
  - 51
  initial_particles: 1000
  output_interval: 100
  time_step: 0.001
  time_steps: 1000
  total_time: 10.0
validation:
  experimental_data_file: data/experimental_data.npz
  sensitivity_analysis:
    compute_interactions: true
    num_samples: 10
    parameter_ranges:
      bond_strength:
      - 0.5e6
      - 2.0e6
      critical_shear_stress:
      - 0.5
      - 2.0
      erosion_rate_coefficient:
      - 5.0e-07
      - 2.0e-06
  statistics:
    compute_basic: true
    compute_correlation: true
    compute_distribution: true
  variables_to_compare:
  - erosion_rate
  - pressure
  - velocity
