# Simulation configuration for DEM-based Internal Erosion Model
simulation:
  time_steps: 1000
  output_interval: 100
  domain_size: [1.0, 1.0, 1.0]
  initial_particles: 100
  gravity: [0.0, -9.81, 0.0]
  time_step: 0.001

dem:
  particle_radius: 0.01
  particle_density: 2650.0
  youngs_modulus: 1e9
  poisson_ratio: 0.3
  friction_coefficient: 0.5
  restitution_coefficient: 0.5

cfd:
  fluid_density: 1000.0
  fluid_viscosity: 1e-6
  pressure_gradient: [0.0, 0.0, 0.0]
  boundary_conditions:
    type: "no-slip"
    velocity: [0.0, 0.0, 0.0]

erosion:
  critical_shear_stress: 0.1
  erosion_rate_coefficient: 1e-6
  transport_capacity: 1.0
  deposition_rate: 0.1

output:
  directory: "results"
  save_particles: true
  save_fluid: true
  visualization_interval: 10
